name: Deploy production
on:
  workflow_dispatch:
  push:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  deploy:
    uses: WillBooster/reusable-workflows/.github/workflows/deploy.yml@main
    with:
      dot_env_path: .env.production
      environment: production
      railway_project_id: 62daa32f-e11c-4b7b-8a2d-3bd7a07e10a7
      railway_service_id: 6740702a-6657-4686-b8ab-2caca3b5b133
      server_url: https://agent-sandbox-app-hosting.up.railway.app/
    secrets:
      DOT_ENV: ${{ secrets.DOT_ENV_PRODUCTION }}
      RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}
